/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb -T 
Files: macbook.glb [629.72KB] > C:\Users\DELL\Desktop\applelanding\public\models\macbook-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import React from 'react'
import * as THREE from 'three'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import useMacbookStore from '@/store';
import { useGSAP } from '@gsap/react'
import { noChangeParts } from '@/constant'

export default function MacbookModel(props: React.ComponentPropsWithoutRef<'group'>) {
  const { color, texture } = useMacbookStore();
  const { nodes, materials, scene } = useGLTF('/models/macbook-transformed.glb') as unknown as {
    nodes: Record<string, THREE.Mesh>
    materials: Record<string, THREE.Material>
    scene: THREE.Scene
  }

  const initialTexture = useVideoTexture('/videos/feature-1.mp4')
  initialTexture.colorSpace = THREE.SRGBColorSpace

  const texturesRef = React.useRef<Record<string, THREE.VideoTexture>>({
    '/videos/feature-1.mp4': initialTexture
  })

  React.useEffect(() => {
    const videoPaths = [
      '/videos/feature-2.mp4',
      '/videos/feature-3.mp4',
      '/videos/feature-4.mp4',
      '/videos/feature-5.mp4',
    ]

    videoPaths.forEach((path) => {
      const video = document.createElement('video')
      video.src = path
      video.muted = true
      video.loop = true
      video.playsInline = true
      video.crossOrigin = 'anonymous'
      video.load()
      video.play().catch((e) => console.log("Preload video play failed:", e))

      const videoTexture = new THREE.VideoTexture(video)
      videoTexture.colorSpace = THREE.SRGBColorSpace
      texturesRef.current[path] = videoTexture
    })

    return () => {
      Object.keys(texturesRef.current).forEach((key) => {
        if (key !== '/videos/feature-1.mp4') {
          const vid = texturesRef.current[key].image as HTMLVideoElement
          vid.pause()
          vid.src = ""
          vid.load()
        }
      })
    }
  }, [])

  const screen = texturesRef.current[texture] || initialTexture
  screen.needsUpdate = true

  useGSAP(() => {
    scene.traverse((child: THREE.Object3D) => {
      if (child instanceof THREE.Mesh) {
        if (!noChangeParts.includes(child.name)) {
          const material = child.material as THREE.MeshStandardMaterial
          if (material && 'color' in material) {
            material.color.set(color)
          }
        }
      }
    })
  }, [color, scene])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.JvMFZolVCdpPqjj} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_123.geometry}  rotation={[Math.PI / 2, 0, 0]} >
       <meshBasicMaterial map={screen}/>
      </mesh>
         {/* <mesh geometry={nodes.Object_123.geometry} material={materials.sfCQkHOWyrsLmor} rotation={[Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/macbook-transformed.glb')
